//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoGit.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHKIEN
    {
        public int MaLK { get; set; }
        public string TenLK { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Mota { get; set; }
        public string Anhbia { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaLLK { get; set; }
        public Nullable<int> MaNSX { get; set; }
    
        public virtual LOAILK LOAILK { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
